#!/bin/bash


#██╗    ██╗ █████╗ ██████╗ ███╗   ██╗██╗███╗   ██╗ ██████╗
#██║    ██║██╔══██╗██╔══██╗████╗  ██║██║████╗  ██║██╔════╝
#██║ █╗ ██║███████║██████╔╝██╔██╗ ██║██║██╔██╗ ██║██║  ███╗
#██║███╗██║██╔══██║██╔══██╗██║╚██╗██║██║██║╚██╗██║██║   ██║
#╚███╔███╔╝██║  ██║██║  ██║██║ ╚████║██║██║ ╚████║╚██████╔╝
# ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝╚═╝  ╚═══╝ ╚═════
### DO NOT SHARE THIS SCRIPT IT HAS PA$$WORDS IN IT !!!!

# lazy cleanup logs older then 5 days
#find /var/log/zm/* -mtime +5 -exec rm '{}' \;

# config

# max number of events over 3000 to trigger smearing
varscorethresh=100

# wait 1 hour for throttling when home
varwait=3600

# default, YOLO only displays objects detected with a confidence of .25 or higher
# set this to .0 to trigger alerts etc
vardarknetthresh=.65
# for debug vardarknetthresh=.1

# START FUNCTIONS ####################################################################################################################################


checksmearing () {
echo `date` DEBUG: Info Checking for smearing
varsmearing=`curl --compressed -i -s -k  -X $'GET'     -H $'Host: 25.0.0.151' -H $'Accept-Encoding: gzip, deflate'      $'http://25.0.0.151/zm/index.php?view=events&page=&reload=0&execute=0&action=&subaction=&line=&fid=&filterName=WIPEALLEVENTS&filter%5Bterms%5D%5B0%5D%5Battr%5D=DateTime&filter%5Bterms%5D%5B0%5D%5Bop%5D=%3C&filter%5Bterms%5D%5B0%5D%5Bval%5D=now&sort_field=DateTime&sort_asc=1&limit=&AutoExecuteCmd=' | grep "colTotScore\">[0-9]" | sed -r 's/(.*ore\">)(.*)(<\/td>)/\2/g'  | egrep "([3-9]...)" |wc -l `
        if [[ "${varsmearing}" -gt "${varscorethresh}" ]]
                then
                        echo `date` DEBUG: Warning Smering triggerd ${varscorethresh} events for scores 3000-9000

                        # restart cam1
                        vartoken=`curl -i -s -k  -X $'POST' --data-binary $'[{\"cmd\":\"Login\",\"action\":0,\"param\":{\"User\":{\"userName\":\"admin\",\"password\":\"\"}}}]' $'http://25.0.0.205/cgi-bin/api.cgi?cmd=Login&token=null'   | grep name |sed -r 's/(.*: \")(.*)(\".*)/\2/g'`
                        curl -v -k  -X $'POST' --data-binary $'[{\"cmd\":\"Reboot\",\"action\":0,\"param\":{}}]' $"http://25.0.0.205/cgi-bin/api.cgi?cmd=Reboot&token=${vartoken}"

                        #restart cam2
                        vartoken=`curl -i -s -k  -X $'POST' --data-binary $'[{\"cmd\":\"Login\",\"action\":0,\"param\":{\"User\":{\"userName\":\"admin\",\"password\":\"\"}}}]' $'http://25.0.0.148/cgi-bin/api.cgi?cmd=Login&token=null'   | grep name |sed -r 's/(.*: \")(.*)(\".*)/\2/g'`
                        curl -v -k  -X $'POST' --data-binary $'[{\"cmd\":\"Reboot\",\"action\":0,\"param\":{}}]' $"http://25.0.0.148/cgi-bin/api.cgi?cmd=Reboot&token=${vartoken}"

                        # restart ZM
                        systemctl stop zoneminder.service;sleep 10;systemctl start zoneminder.service

        fi
}


emailalert () {
echo `date` DEBUG: Info sending email
python /usr/local/sbin/GMAIL.py
export startTime=$(date +%s)
}

checkarp () {
echo `date` DEBUG: Info Checking for Phones
export varHost1=`ping -W 5 -c 1 192.168.20.28 |grep '\b0% packet loss'`
export varHost2=`ping -W 5  -c 1 192.168.20.82 |grep '\b0% packet loss'`


if [ "${varHost1}"  == '' ] && [ "${varHost2}"  == ''  ]
        then
                echo `date` DEBUG: Info status set to away not throttling notifications
                export varstatus=away
        else
                echo `date` DEBUG: Info status set to home throttling notifications
                export varstatus=home
fi


}



GO_DARKNET() {

export vareventpath=`find /var/cache/zoneminder/events -path "*\/*\/*\/*\/*\/*\/*\/*\/*\/*/.${varevenid}*"|sed 's/\..*//g'`
cd /home/plex/YOLO/darknet
echo `date` DEBUG: Info varevenid ${varevenid} Path ${vareventpath}
        for i in `find /usr/share/zoneminder/www/events/*/*/${varevenid}/*.mp4|shuf -n 10`
                do
                        if [[ `mediainfo $i|grep Duration` == "" ]]
                                then
                                        echo `date` DEBUG: Error no duration for ${varevenid} "${i}"
                                else
                                        export vardarknet=`./darknet detector demo ./cfg/coco.data  ./cfg/yolov3.cfg /home/plex/YOLO/darknet/yolov3.weights -dont_show  $i  -thresh ${vardarknetthresh} 2> /dev/null | egrep -ia "(person|cat|dog|car|truck)"`
                                        echo `date` DEBUG: Info running Darknet on ${varevenid} $i
                        fi

killall darknet 2> /dev/null
sleep 2
killall -9 darknet 2> /dev/null

cd "/home/plex/darknet_2021/1/darknet"
unbuffer ./darknet detector demo ./cfg/coco.data ./cfg/yolov3.cfg /home/plex/YOLO/darknet/yolov3.weights -dont_show "${i}" -thresh .65 > out.txt &

COUNTER=1
sleep 1
        while [  $COUNTER -lt 121 ]
                do
                        VAR_OBJECT=`grep '%' out.txt`
                        let COUNTER=COUNTER+1
                                if [[ "${VAR_OBJECT}" != "" ]]
                                        then
                                                echo `date` DEBUG: Info object found in $COUNTER seconds
                                                vardarknet="${VAR_OBJECT}"
                                                #cp "${i}" /tmp/tmp.mp4
                                                ffmpeg -i "${i}" -y -preset slow -codec:a libfdk_aac -b:a 128k -codec:v libx264 -pix_fmt yuv420p -b:v 1000k -minrate 500k -maxrate 2000k -bufsize 2000k -vf scale=854:480 /tmp/tmp.mp4
                                                COUNTER=999
                                        else
                                                echo `date` DEBUG: Warning object not found scanning $COUNTER seconds
                                fi
                        sleep 1
                done

        if [[ "${VAR_OBJECT}" == "" ]]
                then
                        echo `date` DEBUG: Error time expired $COUNTER seconds object not found
                        echo `date` DEBUG: Error killing darknet
                        killall darknet
                        killall -9 darknet

        fi

                done


}

# MAIN  ####################################################################################################################################




tail -F --retry -n 0  /var/log/zm/*.log | while read LOGLINE
do
        echo `date` DEBUG: Info ${LOGLINE}|egrep "(\bzm[a-z])"
        varevenid=`echo ${LOGLINE}| grep "Closing event"  | sed -r 's/(.*Closing event )(.*)(,.*)/\2/g'`
                if [[ "${varevenid}" != "" ]]
                        then
                                # we don't have issues with smearing anymore ....               checksmearing
                                checkarp
                                if [[ "${varstatus}" == "home" && $(($(date +%s) - startTime))  -gt $varwait  ]]
                                        then
                                                echo `date` DEBUG: Info running darknet it has been ${varwait} seconds and startTime is ${startTime}
                                                GO_DARKNET
                                fi

                                if [[ "${varstatus}" == "home" &&  $(($(date +%s) - startTime))  -lt $varwait && $startTime != "" ]]
                                        then
                                                echo `date` DEBUG: Info startTime is ${startTime} null or delay not reached
                                                export vardarknet=""
                                        fi

                                if [[ "${varstatus}" == "away" ]]
                                        then
                                                echo `date` DEBUG: Info running darknet in away status
                                                GO_DARKNET
                                fi


                                if [[ "${vardarknet}" != "" ]]
                                        then
                                                echo `date` DEBUG: Info vardarknet is not null emailing
                                                emailalert
                                fi
                fi
done
