#!/bin/bash


#██╗    ██╗ █████╗ ██████╗ ███╗   ██╗██╗███╗   ██╗ ██████╗
#██║    ██║██╔══██╗██╔══██╗████╗  ██║██║████╗  ██║██╔════╝
#██║ █╗ ██║███████║██████╔╝██╔██╗ ██║██║██╔██╗ ██║██║  ███╗
#██║███╗██║██╔══██║██╔══██╗██║╚██╗██║██║██║╚██╗██║██║   ██║
#╚███╔███╔╝██║  ██║██║  ██║██║ ╚████║██║██║ ╚████║╚██████╔╝
# ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝╚═╝  ╚═══╝ ╚═════╝
### DO NOT SHARE THIS SCRIPT IT HAS PA$$WORDS IN IT !!!!

# lazy cleanup logs older then 5 days
find /var/log/zm/* -mtime +5 -exec rm '{}' \;
find /media/moredata/events/1/* -mtime +15 -exec rm -Rf '{}' \;
find /media/moredata/events/2/* -mtime +15 -exec rm -Rf '{}' \;

# config

# max number of events over 3000 to trigger smearing
varscorethresh=100

# wait 1 hour for throttling when home
varwait=3600

# default, YOLO only displays objects detected with a confidence of .25 or higher
# set this to .0 to trigger alerts etc
vardarknetthresh=.65
# for debug vardarknetthresh=.1

# START FUNCTIONS ####################################################################################################################################


checksmearing () {
echo `date` DEBUG: Info Checking for smearing
varsmearing=`curl --compressed -i -s -k  -X $'GET'     -H $'Host: 25.0.0.151' -H $'Accept-Encoding: gzip, deflate'      $'http://25.0.0.151/zm/index.php?view=events&page=&reload=0&execute=0&action=&subaction=&line=&fid=&filterName=WIPEALLEVENTS&filter%5Bterms%5D%5B0%5D%5Battr%5D=DateTime&filter%5Bterms%5D%5B0%5D%5Bop%5D=%3C&filter%5Bterms%5D%5B0%5D%5Bval%5D=now&sort_field=DateTime&sort_asc=1&limit=&AutoExecuteCmd=' | grep "colTotScore\">[0-9]" | sed -r 's/(.*ore\">)(.*)(<\/td>)/\2/g'  | egrep "([3-9]...)" |wc -l `
        if [[ "${varsmearing}" -gt "${varscorethresh}" ]]
                then
                        echo `date` DEBUG: Warning Smering triggerd ${varscorethresh} events for scores 3000-9000

                        # restart cam1
                        vartoken=`curl -i -s -k  -X $'POST' --data-binary $'[{\"cmd\":\"Login\",\"action\":0,\"param\":{\"User\":{\"userName\":\"admin\",\"password\":\"\"}}}]' $'http://25.0.0.205/cgi-bin/api.cgi?cmd=Login&token=null'   | grep name |sed -r 's/(.*: \")(.*)(\".*)/\2/g'`
                        curl -v -k  -X $'POST' --data-binary $'[{\"cmd\":\"Reboot\",\"action\":0,\"param\":{}}]' $"http://25.0.0.205/cgi-bin/api.cgi?cmd=Reboot&token=${vartoken}"

                        #restart cam2
                        vartoken=`curl -i -s -k  -X $'POST' --data-binary $'[{\"cmd\":\"Login\",\"action\":0,\"param\":{\"User\":{\"userName\":\"admin\",\"password\":\"\"}}}]' $'http://25.0.0.148/cgi-bin/api.cgi?cmd=Login&token=null'   | grep name |sed -r 's/(.*: \")(.*)(\".*)/\2/g'`
                        curl -v -k  -X $'POST' --data-binary $'[{\"cmd\":\"Reboot\",\"action\":0,\"param\":{}}]' $"http://25.0.0.148/cgi-bin/api.cgi?cmd=Reboot&token=${vartoken}"

                        # restart ZM
                        systemctl stop zoneminder.service;sleep 10;systemctl start zoneminder.service

        fi
}


emailalert () {
echo `date` DEBUG: Info sending email
python /usr/local/sbin/GMAIL.py
export startTime=$(date +%s)
}

checkarp () {
echo `date` DEBUG: Info Checking for Phones
# is one of our phones on the network ?
# my phones are on segmented wifi and I cant ping all of them so using this wackado expect telnet script ...
# maybe adjust arp timeout 15min ? echo 900 >/proc/sys/net/ipv4/neigh/default/gc_stale_time

echo "echo XXXXXXXXXXXXXXXXXXXXXXXXXXXX" > /tmp/1
chmod 777 /tmp/1

# sets some vars for ssh to play nice with something to do with GUI but here we are using it to pass creds.


export SSH_ASKPASS="/tmp/1"
export DISPLAY=YOURDOINGITWRONG
export varHost1=`setsid ssh root@25.0.0.1 -p 22 "arp -an" | grep -iaE "(f4:f5:24:3a:31:85|58:d5:0a:29:3c:b8)" | grep on`

if [ "${varHost1}"  == '' ]
then
echo `date` DEBUG: Info status set to AWAY not throttling notifications
export varstatus=away
else
echo `date` DEBUG: Info status set to HOME throttling notifications
export varstatus=home
fi


}



GO_DARKNET() {

export vareventpath=`find /var/cache/zoneminder/events -path "*\/*\/*\/*\/*\/*\/*\/*\/*\/*/.${varevenid}*"|sed 's/\..*//g'`
echo `date` DEBUG: Info varevenid ${varevenid} Path ${vareventpath}
        for i in `find /usr/share/zoneminder/www/events/*/*/${varevenid}/*.mp4|shuf -n 10`
                do
                        if [[ `mediainfo $i|grep Duration` == "" ]]
                                then
                                        echo `date` DEBUG: Error no duration for ${varevenid} "${i}"
                                else
                                        echo `date` DEBUG: Info running Darknet on ${varevenid} $i
                        fi

killall darknet 2> /dev/null
sleep 2
killall -9 darknet 2> /dev/null

cd "/home/plex/YOLO/darknet_AB/darknet"
unbuffer ./darknet detector demo /home/plex/YOLO/darknet_AB/darknet/cfg/coco.data  /home/plex/YOLO/darknet_AB/darknet/cfg/yolov3.cfg /home/plex/YOLO/darknet_AB/darknet/yolov3.weights -dont_show "${i}" -thresh .65 > out.txt &
COUNTER=1
sleep 1
        while [  $COUNTER -lt 121 ]
                do
                        VAR_OBJECT=`grep '%' out.txt| egrep -ia "(person|cat|dog|car|truck)"`
                        let COUNTER=COUNTER+1
                                if [[ "${VAR_OBJECT}" != "" ]]
                                        then
                                                vardarknet="${VAR_OBJECT}"
                                                echo `date` DEBUG: Object "${VAR_OBJECT}" found in $COUNTER seconds
                                                #cp "${i}" /tmp/tmp.mp4
                                                ffmpeg -i "${i}" -y  -preset slow -codec:a libfdk_aac -b:a 128k -codec:v libx264 -pix_fmt yuv420p -b:v 1000k -minrate 500k -maxrate 2000k -bufsize 2000k -vf scale=854:480 /tmp/tmp.mp4
                                                COUNTER=999
                                       #DEBUG else
                                            #DEBUG    echo `date` DEBUG: Warning object not found scanning $COUNTER seconds
                                fi
                        sleep 1
                done

        if [[ "${VAR_OBJECT}" == "" ]]
                then
                        echo `date` DEBUG: Error time expired $COUNTER seconds object not found
                        echo `date` DEBUG: Error killing darknet
                        killall darknet
                        killall -9 darknet

        fi

                done


}

# MAIN  ####################################################################################################################################




tail -F --retry -n 0  /var/log/zm/*.log /media/data/zm.log | while read LOGLINE
do
        echo `date` DEBUG: Info ${LOGLINE}|egrep "(\bzm[a-z])"
        varevenid=`echo ${LOGLINE}| grep "Closing event"  | sed -r 's/(.*Closing event )(.*)(,.*)/\2/g'`
                if [[ "${varevenid}" != "" ]]
                        then
                                # we don't have issues with smearing anymore ....               checksmearing
                                checkarp
                                if [[ "${varstatus}" == "home" && $(($(date +%s) - startTime))  -gt $varwait  ]]
                                        then
                                                echo `date` DEBUG: Info running darknet it has been ${varwait} seconds and startTime is ${startTime}
                                                GO_DARKNET
                                fi

                                if [[ "${varstatus}" == "home" &&  $(($(date +%s) - startTime))  -lt $varwait && $startTime != "" ]]
                                        then
                                                echo `date` DEBUG: Info startTime is ${startTime} null or delay not reached
                                                export vardarknet=""
                                        fi

                                if [[ "${varstatus}" == "away" ]]
                                        then
                                                echo `date` DEBUG: Info running darknet in away status
                                                GO_DARKNET
                                fi


                                if [[ "${vardarknet}" != "" ]]
                                        then
                                                echo `date` DEBUG: Info vardarknet is not null emailing
                                                emailalert
                                fi
                fi
done
